name = "ParamDataBridge"
uuid = "705b3acb-8a53-4641-b534-95e7b7ccac73"
authors = ["Diego N. Bernal-Garcia"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
